server:
  error:
    include-stacktree: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
    username: root
    password: abobora
  jpa:
    hibernate:
      ddl-auto: update

logging:
    level:
      org:
        hibernate:
          SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"



